### ISSUE TITLE
The `toAbsoluteUrl` method in the Storage strategy should have a deterministic behaviour

### ISSUE THREAD

**Issue by skid** [Pinelab-studio/pinelab-vendure-plugins#11]
Just ran into an issue with this code:

https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/634bd4e5643e38642d3fb8bcc542c2703d4ee83a/packages/vendure-plugin-google-storage-assets/src/google-storage-strategy.ts#L27

I have feature where the admin can trigger a reindex of al products into Typesense. The index carries an URL to the product's image, but since the admin triggers it via the admin api, the URL to the image points to the vendure asset server instead of the google bucket.

This behaviour should really be deterministic for all APIs - is there a reason why it points to the local asset server when accessed via the admin api?

**Comment by martijnvdbrug** [comment]
@skid I agree this is not the best solution, but its needed for the following:

The admin UI relies on fixed image sizes. The admin UI requests images in this format:
`/assets/preview/image.jpg?preset=tiny` where the Vendure asset server resizes the image to the correct format for the admin UI.

The absolute URL used in the frontend is a link directly to the Google Bucket, so you can leverage the CDN capabilities. However, the images directly from a bucket cannot be resized with `preset=tiny`, because they do not pass through the asset server.

We could make it configurable with something like `useDirectGoogleLink=true`. This means slower load times for image on the frontend if you are using serverless environments though...

**Comment by martijnvdbrug** [comment]
Good point. I will add it to my TODO list. If you're in a hurry you could create a PR for this ofcourse!

**Comment by skid** [comment]
No urgent, but I will do once I get around to it :)

**Comment by martijnvdbrug** [comment]
Maybe we can skip the assetServer all together with this fix: https://github.com/vendure-ecommerce/vendure/commit/e175f52 

I still have to look into it though.

**Comment by martijnvdbrug** [comment]
It does not fix our issue, but if I understand correctly, it should. I added a comment: https://github.com/vendure-ecommerce/vendure/issues/1514

If this can be fixed in Vendure Admin, then I can remove the `admin` check for `toAbsoluteUrl`

**Comment by martijnvdbrug** [comment]
@skid This issue has been fixed in: https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/32 and release as [vendure-plugin-google-storage-assets@3.3.0](https://www.npmjs.com/package/vendure-plugin-google-storage-assets/v/3.3.0)
@vendure/admin-ui now accepts un-resized images, so the asset-server proxying is now optional:

```js
new GoogleStorageStrategy({
          bucketName: 'pinelab-testing',
          useAssetServerForAdminUi: false
        }),
```
