### ISSUE TITLE
convertOrderToDraft resets customFields

### ISSUE THREAD

**Issue by mschipperheyn** [Pinelab-studio/pinelab-vendure-plugins#342]
**Which plugin/repository is the issue about?**
modify-customer-orders

**Describe the bug**
When you call `convertOrderToDraft` on an order which has customFields set on the oder-line, in our case a relation to customer: `assignedCustomer`, it seems to null those fields. Judging by the code it just copies over quantity and product variant, not additional fields

**To Reproduce**

1. set a customField on an orderline
2. Call convertOrderToDraft
3. Review the state of the customField

**Expected behavior**
This function should maintain the state of the order as is, including customFields

**Screenshots**

**Environment**

- NodeJS version
- Vendure version: 2.1.6
- Plugin version 1.1.0
- Database Postgres
- Any other version numbers from the environment you're using

**Additional context**

**Comment by martijnvdbrug** [comment]
I see indeed that we are copying order-lines [here in the resolver](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/dd1a2c8b1a02a685d2844991efa9930ae4980c07/packages/vendure-plugin-modify-customer-orders/src/api/api.resolver.ts#L53). This copying doesn't take customFields into account.

We could find a way to copy customFields to the new order line, but the issue is bigger than that: We could have custom relations or custom fields on the order itself, or applied promotions etc.

The right approach would be to transition the current order into a Draft order, but the Vendure Default order process doesn't allow this. We could make this plugin install a custom order process with the `mergeStrategy: 'merge'`. That custom order process would then allow converting orders in `AddingItems` to `Draft`.

:-1: An alternative would be to just update de state field in the DB to `Draft`, but this feels hacky and bypasses the entire state machine. I can't see what consequences this might have, so I don't think this is a safe approach.

@dalyathan I think you did the initial setup of this if I'm not mistaken? What are your thoughts on this?

**Comment by dalyathan** [comment]
I also think using a custom order process Is the right approach
