### ISSUE TITLE
How to Remove Gift Products Automatically When Removing Associated Items from Cart?

### ISSUE THREAD

**Issue by zolzaya** [Pinelab-studio/pinelab-vendure-plugins#392]
Currently, when I add a product, the gift product is also added to the cart, but upon removing the product, the gift item remains. How can I ensure that the gift product is removed when its corresponding item is removed from the cart?

**Comment by martijnvdbrug** [comment]
Good point! The item indeed stays in cart, but it's not free anymore, the normal price will be used. The plugin currently doesn't support automatically remove the selected gift. You could manually remove order lines that have `isSelectedAsGift=true` from your storefront.

Alternatively, what you can do is create a custom EventBus listener, that listens for order changes:
1. When an order changes, get `const eligibleGifts = await GiftService.getEligibleGiftsForOrder()` and remove any order lines with `customFields.isSelectedAsGift=true` that do not occur in `eligibleGifts`. 
⚠ This can have some impact on performance, depending on the amount of traffic you have. This is also why this behavior will not be implemented by default in the plugin.

It's difficult to handle this in the plugin, because of the flexibility of the promotions. It is hard to find what product variant was responsible for allowing this gift. Or, in our case, it's dependent on the amount of orders a customer has placed before, so not dependent on an item in the cart at all.
