### ISSUE TITLE
Vendure Plugin for generating invoices is not working

### ISSUE THREAD

**Issue by Altangerel2k** [Pinelab-studio/pinelab-vendure-plugins#404]
I hope this message finds you well. I am currently using the Vendure Plugin to generate invoices and have ensured that the 'AllowInvoicesPermission' is active. However, I'm unable to view the 'Sales > Invoices' section in our system.

Could you please help me understand if there's an additional configuration or step I might be missing? Any guidance or assistance you can provide would be greatly appreciated.

Thank you for your time and support.

**Comment by martijnvdbrug** [comment]
Hi! Thank you for your report. Can you supply some more details? What Vendure version and what plugin version are you using? Steps to reproduce this issue would also be helpful.

**Comment by martijnvdbrug** [comment]
@Altangerel2k The plugin has been updated to use Puppeteer instead of phantomJS. Can you try updating the plugin to V4 to see if the issue persists? Please [read the readme](https://pinelab-plugins.com/plugin/pinelab-invoice-plugin/) though!

Feel free to open a new issue if the issues persists in V4
