### ISSUE TITLE
The `maxRetries` feature is not backwards compatible

### ISSUE THREAD

**Issue by skid** [Pinelab-studio/pinelab-vendure-plugins#58]
**Which plugin is the issue about?**
vendure-plugin-google-cloud-tasks

This is not a bug inasmuch an issue with the default behaviour added in 3.5.0
 
The `maxRetries` default value that was added in 3.5.0 is not backwards compatible. Our implementation depends on the google tasks retry mechanism because one of the 3rd party services we use has a rate limit and we use the backoff mechanism to eventually execute a call. the maxRetries change that was made started dropping tasks after 3 retries.

Additionally - why is a retry mechanism even needed for the plugin, given that Google cloud tasks already has a retry mechanism?

**Comment by martijnvdbrug** [comment]
That change should maybe have been a major version bump.

Anyhow, the change was introduced in [this PR](https://github.com/Pinelab-studio/pinelab-vendure-plugins/pull/35/files), because a Vendure Job accepts a `retries` as input. Before 3.5.0, the given job.retries was ignored and the task was retried based on the configured queue settings in Cloud Tasks.

I think the current behaviour is as expected:
* When I add a worker job in Vendure with `queue.add({}, {retries: 5})`, I don't want the job to be retried 80 times because that is what is configured on Cloud Tasks.

I see I also added a default of 3 retries in [this line of code](https://github.com/Pinelab-studio/pinelab-vendure-plugins/blob/9e74da954d68e975a7b617af008d8c264504bd13/packages/vendure-plugin-google-cloud-tasks/src/cloud-tasks-job-queue.strategy.ts#L32). 

Would it solve your use-case if we make the default number of retries configurable on the plugin? Something like `CloudTasksPlugin.init({defaultRetries: 100});` that will be used when no retries is passed in a job.

**Comment by skid** [comment]
Yes. That should be sufficient.

**Comment by martijnvdbrug** [comment]
@skid in version [3.16.1](https://www.npmjs.com/package/vendure-plugin-google-cloud-tasks) you can now specify a defaultRetries for all tasks, when no job.retries is given. Job.retries will be used if given though.
